# 01. Знакомство с `torch.Tensor`

V 0.1 04.02.2021

__Выполнила Ларькова Дарья__

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [1]:
import torch

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [2]:
board = torch.zeros((8, 8))
board[0] = torch.tensor([-4., -3., -2., -6., -5., -2., -3., -4.])
board[1] = -1.
board[6] = 1.
board[7] = -board[0]
board

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [3]:
even = torch.arange(2, 21, 2)
result = even * (even + 1)
result

tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [4]:
result = torch.arange(1, 111).reshape(11, 10)[:, :7]
result

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [5]:
def texture(n, m):
    pattern = torch.tensor([[0, 1], [2, 3]])
    return pattern.repeat((n + 1) // 2, (m + 1) // 2)[:n, :m]

texture(4, 5)

tensor([[0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2],
        [0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

In [6]:
t = torch.rand((4, 7)) * 20
t_norm = (t - t.min()) / (t.max() - t.min())

print(t)
print(t_norm)
print(t_norm.min(), t_norm.max())

tensor([[ 9.9932,  5.5836,  0.8685,  0.2657,  7.2127, 12.0411,  7.9184],
        [ 0.9257, 18.5807, 19.2246, 12.9953, 19.8072,  3.6980,  4.6994],
        [ 8.2281, 15.1385,  0.0706, 14.2406,  6.9799,  4.2840, 19.3402],
        [ 7.1156,  9.3991,  5.6854,  8.5413, 18.0176,  0.4929,  8.9800]])
tensor([[0.5028, 0.2793, 0.0404, 0.0099, 0.3619, 0.6065, 0.3976],
        [0.0433, 0.9379, 0.9705, 0.6549, 1.0000, 0.1838, 0.2345],
        [0.4133, 0.7635, 0.0000, 0.7180, 0.3501, 0.2135, 0.9763],
        [0.3570, 0.4727, 0.2845, 0.4292, 0.9093, 0.0214, 0.4514]])
tensor(0.) tensor(1.)


[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в массивах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [7]:
ar1 = torch.randint(0, 11, (4, 7))
ar2 = torch.randint(0, 11, (4, 7))
result = torch.maximum(ar1, ar2)

print(ar1)
print(ar2)
result

tensor([[ 2,  8,  1,  5,  6,  6,  8],
        [ 4,  4,  5,  5, 10,  2,  8],
        [ 5,  6,  5,  7,  2, 10,  0],
        [ 7,  5,  7,  8,  8,  6,  7]])
tensor([[ 9,  0, 10,  7,  5,  1,  3],
        [ 9,  6,  5,  6,  0,  2,  2],
        [ 3,  5,  7,  8,  5,  4,  9],
        [ 4,  4,  1, 10,  8,  1,  1]])


tensor([[ 9,  8, 10,  7,  6,  6,  8],
        [ 9,  6,  5,  6, 10,  2,  8],
        [ 5,  6,  7,  8,  5, 10,  9],
        [ 7,  5,  7, 10,  8,  6,  7]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [8]:
t = torch.randint(0, 101, (20,))
values, indices = torch.topk(t, 2)

print(t)
print("Второе сверху значение:", values[1].item())
print("Индекс:", indices[1].item())

tensor([37, 40, 56,  7, 62, 42,  1, 65, 63, 68, 89, 65, 13, 48, 96, 57, 20, 62,
        43, 49])
Второе сверху значение: 89
Индекс: 10


## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [9]:
rows = torch.arange(0, 11).reshape(-1, 1) * 10
cols = torch.arange(1, 8)
result = rows + cols
result

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [10]:
a_2d = torch.tensor([[3, 3, 3],
                     [4, 4, 4],
                     [5, 5, 5]])
b_1d = torch.tensor([1, 2, 3])

result = a_2d - b_1d.reshape(-1, 1)
result

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
array([1, 3, 5, 7])
```

In [11]:
a = torch.tensor([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = torch.tensor([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

indices = torch.nonzero(a == b, as_tuple=True)[0]
indices

tensor([1, 3, 5, 7])

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [12]:
a = torch.arange(9).view(3, 3)
result = torch.flip(a, dims=(0, 1))
result

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

Ожидается резульат:

```python
array([6, 9, 10])
```

In [13]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
result = a[(a >= 5) & (a <= 10)]
result

tensor([ 6,  9, 10])

1.3.4 Поменять местами столбец 1 и 2 тензора `np.arange(9).reshape(3,3)`

In [14]:
a = torch.arange(9).reshape(3, 3)
result = a[:, [0, 2, 1]]
result

tensor([[0, 2, 1],
        [3, 5, 4],
        [6, 8, 7]])

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [15]:
a = torch.randint(0, 11, (8, 10))
row_sums = a.sum(dim=1)
row_index = torch.argmin(row_sums)

print(a)
print("Индекс строки:", row_index.item())
print("Строка:", a[row_index])
print("Сумма:", row_sums[row_index].item())

tensor([[ 0,  7,  7,  9,  5,  5,  8,  1,  4, 10],
        [ 8, 10,  9,  8,  5,  4,  6,  2,  9,  6],
        [ 7,  6,  0,  3,  9,  3,  8,  8,  7, 10],
        [ 0,  9,  9,  7,  1,  6,  4,  1, 10,  3],
        [ 3,  6,  8, 10,  2,  6, 10,  0,  0, 10],
        [ 8,  1,  3, 10,  1,  8,  7, 10,  7,  3],
        [ 0,  4,  2,  0,  5,  2,  9,  5, 10,  3],
        [ 3,  0,  1,  9,  4,  6,  3,  5, 10,  4]])
Индекс строки: 6
Строка: tensor([ 0,  4,  2,  0,  5,  2,  9,  5, 10,  3])
Сумма: 40


1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [16]:
a = torch.randint(0, 101, (20,))
result = torch.clamp(a, 30, 70)

print(a)
result

tensor([59, 38,  3, 48,  6,  9, 46, 62, 90, 43, 77, 87, 22, 25, 99, 17,  3, 11,
        23, 18])


tensor([59, 38, 30, 48, 30, 30, 46, 62, 70, 43, 70, 70, 30, 30, 70, 30, 30, 30,
        30, 30])

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [17]:
ar1 = torch.randint(0, 11, (30, 3))
ar2 = torch.randint(0, 11, (30, 3))
values = ar1[ar1 > ar2]

print(values)
print("Сумма:", values.sum().item())

tensor([ 7,  9,  5,  6, 10,  7,  8,  9,  5, 10,  9,  9,  9,  7, 10,  4, 10,  7,
         4,  7,  6,  8,  7, 10,  3,  5,  3,  7,  5,  8,  6,  8, 10,  7,  9, 10,
        10,  9,  5])
Сумма: 288


1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [18]:
a = torch.randint(0, 11, (20, 20))
idx = torch.arange(19)
result = a[idx, idx + 1]
result

tensor([ 9,  3,  0,  7,  5,  0,  2,  6,  2,  9,  1,  1, 10,  8,  5,  9,  8,  5,
         4])

1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [19]:
ar1 = torch.randint(0, 11, (5, 10))
ar2 = torch.randint(0, 11, (5, 10))
mask = ar1 == ar2

print(ar1)
print(ar2)

ar1[mask] *= 2
ar1

tensor([[ 7,  3,  7,  5,  5,  6,  2,  5, 10,  2],
        [ 6,  4,  0,  0,  7,  5,  6,  9,  6,  7],
        [ 4,  0, 10,  2,  0,  8,  8,  3, 10, 10],
        [ 3,  6,  3,  9,  0,  5,  8,  5,  5, 10],
        [ 8,  8,  0,  6,  1,  5,  7,  1,  1,  9]])
tensor([[10,  8, 10,  3,  9,  4,  1,  3,  9,  4],
        [ 2,  6,  4,  7, 10,  0,  0,  8,  2,  4],
        [ 8,  2,  0, 10,  5,  6,  6,  9,  0,  4],
        [ 6,  0,  0,  8,  5,  0,  8,  8,  3,  1],
        [ 2,  1,  8,  7,  1,  8,  2,  0,  7,  2]])


tensor([[ 7,  3,  7,  5,  5,  6,  2,  5, 10,  2],
        [ 6,  4,  0,  0,  7,  5,  6,  9,  6,  7],
        [ 4,  0, 10,  2,  0,  8,  8,  3, 10, 10],
        [ 3,  6,  3,  9,  0,  5, 16,  5,  5, 10],
        [ 8,  8,  0,  6,  2,  5,  7,  1,  1,  9]])

1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [20]:
ar1 = torch.randint(0, 11, (4, 7))
ar2 = torch.randint(0, 11, (4, 7))
ar3 = torch.randint(0, 11, (4, 7))

mask = (ar1 > ar2) & (ar1 < ar3)
ar1[mask] = 0
ar1

tensor([[10, 10,  1, 10,  0,  9,  1],
        [10, 10,  6,  4,  5,  7,  0],
        [ 0, 10,  8,  4,  0,  1,  6],
        [ 0,  1,  9,  0,  5,  1,  6]])

1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [21]:
ar1 = torch.randint(0, 21, (20, 5))
row_max = ar1.max(dim=1, keepdim=True).values
max_mask = ar1 == row_max
counts = max_mask.sum(dim=0)
columns = torch.nonzero(counts >= 5, as_tuple=True)[0]

print(ar1)
print("Количество максимумов по столбцам:", counts)
print("Искомые столбцы:", columns)

tensor([[15,  8,  2,  8, 18],
        [17, 18, 10,  6, 10],
        [11,  7, 16,  7, 11],
        [10,  0, 20,  2,  9],
        [ 4, 18, 16, 17,  7],
        [10, 10,  3, 10, 10],
        [12,  5, 20, 15, 19],
        [ 1,  3,  1, 14,  3],
        [15, 18,  9,  8,  9],
        [15,  6, 12,  1, 17],
        [ 6, 11, 19, 15, 19],
        [ 2, 13, 17, 16,  8],
        [15,  1, 13, 19, 19],
        [13, 11, 15, 11,  1],
        [ 3,  6, 13, 14,  1],
        [18,  0, 18, 15,  1],
        [ 8,  4, 14,  2, 14],
        [16, 19,  6,  0, 14],
        [ 0, 20,  1, 20,  8],
        [ 0, 15, 10,  7, 12]])
Количество максимумов по столбцам: tensor([2, 7, 8, 5, 6])
Искомые столбцы: tensor([1, 2, 3, 4])


1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива. 

In [22]:
ar1 = torch.rand((4, 7))
max_index = torch.argmax(ar1)
row = max_index // ar1.shape[1]
col = max_index % ar1.shape[1]

rows = torch.arange(ar1.shape[0]).reshape(-1, 1)
cols = torch.arange(ar1.shape[1])
mask = (rows > row) & (cols > col)

print(ar1)
ar1[mask] = 0
print("Максимум находится в позиции:", (row.item(), col.item()))
ar1

tensor([[0.2446, 0.5510, 0.1756, 0.9928, 0.6543, 0.6963, 0.9420],
        [0.2568, 0.7487, 0.3562, 0.0836, 0.0479, 0.2978, 0.2579],
        [0.9807, 0.6159, 0.0293, 0.6645, 0.5803, 0.5551, 0.8808],
        [0.0963, 0.8155, 0.1825, 0.3145, 0.7113, 0.6322, 0.7160]])
Максимум находится в позиции: (0, 3)


tensor([[0.2446, 0.5510, 0.1756, 0.9928, 0.6543, 0.6963, 0.9420],
        [0.2568, 0.7487, 0.3562, 0.0836, 0.0000, 0.0000, 0.0000],
        [0.9807, 0.6159, 0.0293, 0.6645, 0.0000, 0.0000, 0.0000],
        [0.0963, 0.8155, 0.1825, 0.3145, 0.0000, 0.0000, 0.0000]])

1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

Пример:

для тензора `torch.tensor([2, 3, 2, 2, 2, 1])`.

Ожидается результат:

```python
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
```

In [23]:
a = torch.tensor([2, 3, 2, 2, 2, 1])
result = torch.nn.functional.one_hot(
    a - 1,
    num_classes=int(a.max())
).float()
result

tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая. 

In [24]:
arr = torch.randint(0, 101, (20,))
counts = torch.bincount(arr)
max_count = counts.max()
modes = torch.nonzero(counts == max_count, as_tuple=True)[0]

mode = modes.min()
indices = torch.nonzero(arr == mode, as_tuple=True)[0]

print(arr)
print("Самые частые значения:", modes)
print("Выбранное значение:", mode.item())
print("Индексы:", indices)

arr_tie = torch.tensor([4, 4, 7, 7, 1, 2])
counts_tie = torch.bincount(arr_tie)
modes_tie = torch.nonzero(counts_tie == counts_tie.max(), as_tuple=True)[0]
print("Пример с двумя модами:", modes_tie)
print("Выбираем наименьшую:", modes_tie.min().item())

tensor([ 1, 38, 96, 25, 78, 87, 20, 94, 73, 48, 96, 26, 66, 57, 71, 32, 22, 69,
        51, 28])
Самые частые значения: tensor([96])
Выбранное значение: 96
Индексы: tensor([ 2, 10])
Пример с двумя модами: tensor([4, 7])
Выбираем наименьшую: 4


## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [25]:
x = torch.linspace(0, 10, 100001)
mask = x * torch.sin(x) > 0.5
part = mask.float().mean()

print("Доля интервала:", part.item())
print("В процентах:", part.item() * 100)

Доля интервала: 0.5241147875785828
В процентах: 52.411478757858276


1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

In [26]:
numbers = torch.arange(2, 101)
divisors = torch.arange(2, 11)

is_composite = ((numbers[:, None] % divisors == 0) &
                (numbers[:, None] != divisors)).any(dim=1)

primes = numbers[~is_composite]
primes

tensor([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61,
        67, 71, 73, 79, 83, 89, 97])

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

In [27]:
a = torch.tensor([1., 2., 3., 4.])
b = torch.tensor([4., 2., 0., 1.])

distance = torch.sqrt(((a - b) ** 2).sum())
distance

tensor(5.1962)

1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100. 
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

In [28]:
a = torch.randint(0, 101, (20, 3))
lengths = torch.sqrt((a.float() ** 2).sum(dim=1))
indices = torch.argsort(lengths)

print("Исходный тензор:")
print(a)
print("Длины:")
print(lengths)
print("Отсортированный тензор:")
print(a[indices])

Исходный тензор:
tensor([[ 60,   5,  17],
        [ 65,  71,  22],
        [ 63,  40,  97],
        [ 93,  62,  85],
        [100,   4,  30],
        [ 48,  61,  71],
        [ 38,   7,  16],
        [ 83,  14,   2],
        [ 72,  99,  30],
        [  1,  13,  78],
        [ 52,  42,  52],
        [  9,  57,  36],
        [ 54,  74,  93],
        [ 71,   8,  90],
        [ 25,  99,   3],
        [ 64,  36,   0],
        [ 81,  98,  89],
        [ 89,  75,   4],
        [ 95,  41,   2],
        [ 99,  49,  76]])
Длины:
tensor([ 62.5620,  98.7421, 122.3846, 140.4208, 104.4797, 105.1951,  41.8210,
         84.1962, 126.0357,  79.0822,  84.6877,  68.0147, 130.5412, 114.9130,
        102.1518,  73.4302, 155.1967, 116.4560, 103.4891, 134.0821])
Отсортированный тензор:
tensor([[ 38,   7,  16],
        [ 60,   5,  17],
        [  9,  57,  36],
        [ 64,  36,   0],
        [  1,  13,  78],
        [ 83,  14,   2],
        [ 52,  42,  52],
        [ 65,  71,  22],
        [ 25,  99,   3],
 

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

In [29]:
a = torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])
mask = (a[1:-1] > a[:-2]) & (a[1:-1] > a[2:])
indices = torch.nonzero(mask, as_tuple=True)[0] + 1

print("Индексы локальных максимумов:", indices)
print("Локальные максимумы:", a[indices])

Индексы локальных максимумов: tensor([2, 5])
Локальные максимумы: tensor([7, 6])


1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

In [30]:
import numpy as np

arr = np.random.rand(100)
value = 0.5

t = torch.from_numpy(arr)
index = torch.argmin(torch.abs(t - value))
closest = t[index]

print("Заданное число:", value)
print("Ближайшее число:", closest.item())
print("Индекс:", index.item())

Заданное число: 0.5
Ближайшее число: 0.5025525624193568
Индекс: 65


1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [31]:
A = torch.tensor([[-1., 2., 4.],
                  [-3., 1., 2.],
                  [-3., 0., 1.]])
B = torch.tensor([[3., -1.],
                  [2.,  1.]])
C = torch.tensor([[7., 21.],
                  [11., 8.],
                  [8., 4.]])

Y = torch.linalg.solve(A, -C)
X = torch.linalg.solve(B.T, Y.T).T

print("X =")
print(X)
print("Проверка A @ X @ B =")
print(A @ X @ B)

X =
tensor([[ 1.0000e+00, -2.1458e-07],
        [-2.0000e+00,  1.0000e+00],
        [ 3.0000e+00, -4.0000e+00]])
Проверка A @ X @ B =
tensor([[ -7.0000, -21.0000],
        [-11.0000,  -8.0000],
        [ -8.0000,  -4.0000]])


1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

In [32]:
vectors = torch.tensor([[3.,  2., 1.,  5.],
                        [-3., 2., 2., -4.],
                        [0.,  4., 3.,  1.],
                        [7.,  7., 4.,  3.]], dtype=torch.float64)

rank = torch.linalg.matrix_rank(vectors)
print("Ранг системы:", rank.item())
print("Число векторов:", vectors.shape[1])
print("Линейно зависима:", rank < vectors.shape[1])

Ранг системы: 3
Число векторов: 4
Линейно зависима: tensor(True)


1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами. 

In [33]:
data = torch.normal(mean=0., std=10., size=(200,)).round().to(torch.int64)
hist, bin_edges = torch.histogram(data.float(), bins=20)

print("Тензор:")
print(data)
print("Гистограмма:")
print(hist)
print("Границы бинов:")
print(bin_edges)

Тензор:
tensor([ -5, -16,  -7,   6,  -2,   1, -14,   6,  -1,   4, -10, -16,  -2, -11,
          0,   7,   8,  22,   6,  -4,  -6,   4,  -3,   0,   3,  19,   1, -11,
          0, -28,  -3, -11, -20,  -2,  10,  14,   8,  -4,  -4, -12,  21,   3,
          6, -21, -15,   7,  -5,  -3,   8,  13,  12,  20,  13, -12,  15,  -1,
         10,  -3,   5,   2,  -4,   0, -27,   3, -14,  -4,  -8,   8,   5, -12,
          0, -17,   3,   2,   0,  23,   4,  -4,  16,   4,  21,  -8,   3, -21,
         -4,   9,  -3, -12,   8, -11,  10,   1,   8,  -1,  14,  -2,  16,   6,
          1,   7,   2,   8,  -1, -13,   4, -12,  19,  -6,   2, -20,  14, -20,
         -7,  17,  12, -17,   8,  24,   0,   2,   8,  -1,  -4,   5, -20, -13,
         18,   2,   5,  14, -10,   0,   1, -12,  10,   5,  -2,  15,  -1, -24,
         -1,  17,  -6,  12,   1,  16,   4,   2, -10,  10,   3, -17,   3, -14,
        -11,  -6,  -9, -13,  -2,  -6,   7,   1,   8,   9,   9,  -4,   7,   6,
        -15,  10,  10,  22,   1,   3,  13,   4,  -6,  14

## Обратная связь
- [ ] Почта: d83073452@yandex.ru
- [ ] Gmail: 3073452@gmail.com
- [ ] Telegram: @sleepingzzzZ